#!/bin/bash
echo "🔐 Final Steps to Complete Setup"
echo ""
echo "1. Create GitHub Token for GH_TOKEN secret:"
echo "   https://github.com/settings/tokens/new"
echo "   - Name: AGS Publisher"
echo "   - Permissions: repo (full control)"
echo "   - Copy the token"
echo ""
echo "2. Set the secret:"
echo "   gh secret set GH_TOKEN"
echo "   (paste the token when prompted)"
echo ""
echo "3. Deploy to Vercel:"
echo "   cd ../biible-content-site"
echo "   vercel login"
echo "   vercel --prod"
echo ""
echo "4. Test the workflow:"
echo "   Go to: https://github.com/ultimatecodemaster/biible-growth-system/actions"
echo "   Click 'AGS - Autonomous Growth System'"
echo "   Click 'Run workflow'"
